# Generated by Django 5.2.6 on 2025-09-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="latitude",
            field=models.FloatField(default=11.25),
        ),
        migrations.AddField(
            model_name="report",
            name="longitude",
            field=models.FloatField(default=75.78),
        ),
    ]
