# Generated by Django 5.2.6 on 2025-09-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_report_latitude_report_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="is_official",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="report",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="report",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="report",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
